// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfbUu6Vk0AtafuYdWkA963NKBuAurdJI4',
    appId: '1:190557213335:web:0d3b461cb8fee944588fd2',
    messagingSenderId: '190557213335',
    projectId: 'txtheta',
    authDomain: 'txtheta.firebaseapp.com',
    storageBucket: 'txtheta.firebasestorage.app',
    measurementId: 'G-JZG6RFLEG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw3mR8-uIHrcGGIhP8nmo0CPgDfArvc2Y',
    appId: '1:190557213335:android:134cc2c9ed634e49588fd2',
    messagingSenderId: '190557213335',
    projectId: 'txtheta',
    storageBucket: 'txtheta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBUm3G_Q9ko5PTnJksNkRnNU7Yn4E8Uh4',
    appId: '1:190557213335:ios:0df4e107bdd910f1588fd2',
    messagingSenderId: '190557213335',
    projectId: 'txtheta',
    storageBucket: 'txtheta.firebasestorage.app',
    iosBundleId: 'com.example.phi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBUm3G_Q9ko5PTnJksNkRnNU7Yn4E8Uh4',
    appId: '1:190557213335:ios:0df4e107bdd910f1588fd2',
    messagingSenderId: '190557213335',
    projectId: 'txtheta',
    storageBucket: 'txtheta.firebasestorage.app',
    iosBundleId: 'com.example.phi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfbUu6Vk0AtafuYdWkA963NKBuAurdJI4',
    appId: '1:190557213335:web:74f569568a0fefcd588fd2',
    messagingSenderId: '190557213335',
    projectId: 'txtheta',
    authDomain: 'txtheta.firebaseapp.com',
    storageBucket: 'txtheta.firebasestorage.app',
    measurementId: 'G-9MMFFTC6JZ',
  );
}
